/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const SettingsLazyRouteImport = createFileRoute('/settings')()
const MemoryLazyRouteImport = createFileRoute('/memory')()
const DevicesLazyRouteImport = createFileRoute('/devices')()
const ChatLazyRouteImport = createFileRoute('/chat')()
const AutomationLazyRouteImport = createFileRoute('/automation')()
const IndexLazyRouteImport = createFileRoute('/')()

const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const MemoryLazyRoute = MemoryLazyRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/memory.lazy').then((d) => d.Route))
const DevicesLazyRoute = DevicesLazyRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/devices.lazy').then((d) => d.Route))
const ChatLazyRoute = ChatLazyRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chat.lazy').then((d) => d.Route))
const AutomationLazyRoute = AutomationLazyRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/automation.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/automation': typeof AutomationLazyRoute
  '/chat': typeof ChatLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/memory': typeof MemoryLazyRoute
  '/settings': typeof SettingsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/automation': typeof AutomationLazyRoute
  '/chat': typeof ChatLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/memory': typeof MemoryLazyRoute
  '/settings': typeof SettingsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/automation': typeof AutomationLazyRoute
  '/chat': typeof ChatLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/memory': typeof MemoryLazyRoute
  '/settings': typeof SettingsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/chat'
    | '/devices'
    | '/memory'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/automation' | '/chat' | '/devices' | '/memory' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/automation'
    | '/chat'
    | '/devices'
    | '/memory'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AutomationLazyRoute: typeof AutomationLazyRoute
  ChatLazyRoute: typeof ChatLazyRoute
  DevicesLazyRoute: typeof DevicesLazyRoute
  MemoryLazyRoute: typeof MemoryLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AutomationLazyRoute: AutomationLazyRoute,
  ChatLazyRoute: ChatLazyRoute,
  DevicesLazyRoute: DevicesLazyRoute,
  MemoryLazyRoute: MemoryLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
